cp3-llbb/CommonTools

README.md
plotUtils/plots/leptons_iso.json
setup.sh

+ minor modif of isolation plot xrange

Add readme and setup

---

plotUtils/.gitignore
plotUtils/README.md
plotUtils/createHistoWithMultiDraw.cpp
plotUtils/external/build-external.sh
setup_env.sh

Some improvements, see commits for more details.

Various improvements

---

plotUtils/Makefile
plotUtils/createHistoWithMultiDraw.cpp
plotUtils/plots/example.py

This is #14 but modified to take @swertz modification into account (a list instead of a dict)

Add support for plots definition in a python script

---

histFactory/src/createHistoWithMultiDraw.cpp

Title says everything. There's a bunch of comment inside the code to understand the issues and what solution are proposed.
I run-tested it and it now works when loading pyroot \o/

Another round of fixes for PyROOT

---

histFactory/cmake/modules/BuildExternals.cmake

No idea how it works previously, but sorry for this one ...

Update TMultiDrawTreePlayer to v1.1.2

---

histFactory/condorExample.py
histFactory/condorTools.py
histFactory/test/plots.py

Adapter condor tools (including the hadd script) for multi run and arbitrary output file names.

Condor for multi run

---

histFactory/condorTools.py
histFactory/plots/TTAnalysis/generatePlots.py
histFactory/plots/TTAnalysis/plotTools.py

Small bugfix in condorTools

---

histFactory/plots/HHAnalysis/basePlotter.py
histFactory/plots/HHAnalysis/generatePlots.py

Modification to hh plotter
Allow to launch createPlotter.sh from elsewhere than build
Z peak veto and improvement in the plotter

Small improvement of the hh plotter

---

treeFactory/.gitignore
treeFactory/CMakeLists.txt
treeFactory/README.md
treeFactory/cmake/modules/BuildExternals.cmake
treeFactory/cmake/modules/CMSSW.cmake
treeFactory/cmake/modules/CMakeCheckCompilerFlagCommonPatterns.cmake
treeFactory/cmake/modules/CMakeParseArguments.cmake
treeFactory/cmake/modules/CP3Dictionaries.cmake
treeFactory/cmake/modules/CheckCXXCompilerFlag.cmake
treeFactory/cmake/modules/FindPythonLibs.cmake
treeFactory/cmake/modules/FindROOT.cmake
treeFactory/scripts/createSkimmer.sh.in
treeFactory/scripts/parallelizedSkimmer.py.in
treeFactory/skimmer/createSkimmer.cc
treeFactory/src/config.h.in
treeFactory/templates/CMakeLists.txt
treeFactory/templates/Skimmer.cc.tpl
treeFactory/templates/Skimmer.h.tpl
treeFactory/templates/generateHeader.sh
treeFactory/test/plots.py
treeFactory/test/sample.json
treeFactory/test/tree.py

This is basically a clone of the tool that create the plotter, but for creating a skimmer. A skimmer is a tool reading a tree and creating another tree. The structure of the output tree is given in a python script (see `test/tree.py`).
No clone of the input tree is done: a new tree is created from scratch, and only the branches given in the python script are created.
See README.md for more details.
@BrieucF @OlivierBondu This is for you guys ;)

Add new tool to generate skimmer

---

histFactory/src/createPlotter.cpp

Split first the string around `:`, and then evaluate the formula on each token.

Split draw string before evaluating the formula

---

histFactory/src/createPlotter.cpp

Add the possibility to specify variable bin size. In the python config, instead of
```
'binning': '(3,0,3)'
```
do
```
'binning': '(2,{0,1,3})'
```
Works for 1D, 2D & 3D histograms (just follow the syntax "nBins,{}" sequentially for each dimension).

Variable bin size

---

histFactory/src/createPlotter.cpp
histFactory/templates/Plotter.cc.tpl

Small fixes: I didn't test every possible use case yesterday (plus, this confusing TH2F with bin limits defined as double, not float). Sorry for the noise...

Fix for sample cut & variable bin size

---

histFactory/plots/ZAAnalysis/generatePlotsJSON_v2.py

For now, this script is denoted _v2, can be later on replacing the original one. 
It allows to run on the three dilepton flavors without increasing too much the script size. For loops+lists are used and make the production of the plot*py/yml more under control.

New version of the plotJSon generator

---

histFactory/.gitignore
mvaTraining/.gitignore
mvaTraining/HHAnalysis/Makefile
mvaTraining/HHAnalysis/train.cc
treeFactory/.gitignore

this PR is essentially for bookkeeping of what was presented during the [HWW mini workshop](https://indico.cern.ch/event/447448/other-view?view=standard#2015-11-24)
the code is likely to evolve quite a bit :)

Mva training

---

histFactory/plots/TTAnalysis/basePlots.py
histFactory/plots/TTAnalysis/generatePlots.py

[TTAnalysis] update plots

---

histFactory/createSampleJson.py

As title says. Currently, when using `createSampleJson.py`, the sum of event weight and cross-section are stored, and `histFactory` automatically rescale histograms accordingly. This PR change this behavior by making this rescaling optional. By default, none is applied: one must use the `-s / --rescale` flag to `createSampleJson.py` to store rescaling information into the JSON file.
Additionally, apply the rescaling only on MC dataset, and not on everything as it was the case.

Make rescaling of histograms optional

---

histFactory/plots/HHAnalysis/ScaleFactors.py
histFactory/plots/HHAnalysis/basePlotter.py
histFactory/plots/HHAnalysis/generatePlots.py
histFactory/plots/HHAnalysis/mapFacilities.py

* Improve naming convention 
* Introduce scale factors for muons and b-jets

Scale factors

---

histFactory/plots/HHAnalysis/basePlotter.py
mvaTraining/HHAnalysis/mergeMVA.py
mvaTraining/HHAnalysis/trainMVA.py
mvaTraining/tmvaTools.py
treeFactory/test/HHAnalysis/generateTrees.py

* First commit for TMVA Pyroot tools. Allows to train a MVA passing the type of method(s) in argument and to merge the output into existing tree as a second step. Example can be found in mvaTraining/HHAnalysis/trainMVA.py and mvaTraining/HHAnalysis/mergeMVA.py .
* Skimmer for HH using the basePlotter to define the tree structure

Skimmer and Pyroot TMVA

---

toolBox/drawCanvas.py
toolBox/rocCurveFacility.py

Here are some pyroot function to produce and draw roc curves. You can see an example of utilisation here : https://github.com/cp3-llbb/HHTools/blob/master/rocCurve_hh/rocCurve_diffFrac.py . It could of course be greatly improved (especially the DrawCanvas part) but it is working.

Roc Curve Facility

---

scripts/plotFrameworkJSON.py

Fix wrong errors as shown in #85

Fix mistake in projection's errors computation

---

histFactory/CMakeLists.txt

It's now possible to build `histFactory` with `make -j200` :smile:

Fix histFactory multi-core build

---

histFactory/templates/Plotter.h.tpl

Fix a weird crash when running with clang
cc @BrieucF

Fix template specialization of fill for clang

---

histFactory/src/createPlotter.cpp
treeFactory/src/createSkimmer.cc
treeFactory/templates/CMakeLists.txt.tpl
treeFactory/templates/Skimmer.cc.tpl
treeFactory/templates/Skimmer.h.tpl

Features ported:
- Sample cut (from a formula in json)
- Sample weight: creates a new branch called "sample_weight" in the output tree, and which is filled with per-events weights depending on the key given in the sample json, just as in histFactory
- Fix for user code include

Porting histFactory features to treeFactory

---

histFactory/templates/Plot.tpl
scripts/createScaleSystematics.py
scripts/flattenTH2.py
toolBox/drawCanvas.py

- histFactory: **force data weights to 1**
- scripts:
- `createScaleSystematics.py`: ensure it can be run twice on the same file
- add `flattenTH2.py`: 'flatten' TH2s to TH1s, ie transform a (nx, ny) histogram to a (nx*ny, 1) histogram -> do 2D fits with TH1s (simpler!)

Add flatten script, some fixes

---

histFactory/condorTools.py
scripts/flattenTH2.py

There was a small bug (range of flattened histo not computed correctly).

Small fix to flatten script

---

toolBox/drawCanvas.py
toolBox/rocCurveFacility.py

Fix computation of significance

---

python/CMSStyle.py
toolBox/rocCurveFacility.py

Small fixes

---

scripts/plotFrameworkJSON.py

argparse ROOT-workaround

---

Factories/src/HistFactory.cc
Factories/src/TreeFactory.cc
Factories/templates/Main.cc.tpl

This can be useful to be able to retrieve this information later on.

Save xsec and normalization into output file

---

python/condorTools.py
scripts/checkJobsAndResubmit.py

This fixes a small bug in the script doing the hadd after the jobs are done that's been there for a long time...
I've also changed the 'checkJobsAndResubmit' script: I always forgot what arguments it expected...

Small fixes in condor tools

---

Factories/src/Factory.cc
Factories/src/HistFactory.cc
Factories/templates/Main.cc.tpl

This PR makes the output of factories a bit more verbose:
- Print when the generation is done. Currently it's not clear if the code succeeded or not
- Force progress output every 5% instead of a random number of events

Improve output

---

Factories/templates/Main.cc.tpl
python/condorTools.py

* Allow to take weight from Sample instead of file (useful to run on skimmed sample)
* Fix a seg fault when running on few events (report_fraction was equal to 0)

Weight from sample

---

Factories/templates/CMakeLists.txt.tpl

useful if one wants to use python inside the factories

Link factories against python and boost::python

---

python/condorTools.py
scripts/checkJobsAndResubmit.py
scripts/createScaleSystematics.py

Some small fixes

---

Factories/templates/Main.cc.tpl

It may helps to solve current issues causing heavy I/O load on storage servers.

Increase tree cache

---

mvaTraining/tmvaTools.py
python/HistogramTools.py
scripts/checkJobsAndResubmit.py
scripts/createScaleSystematics.py
scripts/flattenTH2.py

- tmva tools: possibility to specify number of test/training events
- scale systematics: small fix to take into account under/overflow and be able to work on TH2's
- `flattenTH2`: ad-hoc possibility to "drop" a few bins along the X axis when flattening the TH2
- `checkJobsAndResubmit`: also check if all the output files are there (not very robust if the same plotter is used several times or if a resubmit was issued)
- `HistogramTools`: add a wrapper around `TFile` to make `TFile::Get` *much* faster. Credit goes to @blinkseb

Several minor updates

---

python/condorTools.py
python/samadhi_imports.py
scripts/createSampleJson.py

fixes https://github.com/cp3-llbb/CommonTools/issues/10

Add checks and error messages for CMSSW, SAMADhi

---

python/slurmTools.py
slurm/slurmExample.py

First steps to support slurm instead of condor. It's untested for the moment, but it's already a starting point. The part doing the `hadd` needs to be rewritten, but I expect the rest to be (more or less) functional.
TODO:

Add tools for submitting jobs on slurm

---

python/slurmTools.py

Two things in this PR:
* First is in the title. It prevents the jobs from writing in real time to remote locations.
* Second is a re-implementation of a lost feature when moving from condor to slurm. The goal is to allow taking the `event-weight-sum`, `extras-event-weight-sum`, etc, directly from the DB instead of recomputing them from each file we run on. If you use this feature, you **must** run on the full sample otherwise the `event-weight-sum`, etc, will not be correct anymore. Default behavior has not changed.

[Slurm] Write the output rootfile on node and mv it at the end

---

Factories/templates/CMakeLists.txt.tpl
cmake/modules/FindGSL.cmake

Here the changes I needed to get the HH plotter to build again...

Fix plotter build
