cp3-llbb/CommonTools

histFactory/src/createHistoWithMultiDraw.cpp

When loading pyROOT inside the python config file, `histFactory` crashes inside the `TTree` constructor. It's because for obscure reasons, `gDirectory` is set to `NULL` when the python env is destroyed.
As a workaround, save the value of `gDirectory` before loading the script and restore it after.

Protect against NULL gDirectory when parsing python script

---

histFactory/CMakeLists.txt
histFactory/cmake/modules/BuildExternals.cmake
histFactory/src/createHistoWithMultiDraw.cpp

When drawing more than one histogram, it happends that some are filled
with wrong values. Root cause is not yet fully understood, but v1.1.1
of TMultiDrawTreePlayer seems to fix the issue. When this occurs, the
TTreeFormula used to fill the histogram returns incorrect values.
Closes #26 
@swertz Can you confirm it solves your issue? From my test, it seems so, but another :+1: would be great!

Fix multi-histogram drawing

---

histFactory/README.md
histFactory/condorExample.py
histFactory/condorTools.py
histFactory/createSampleJson.py
histFactory/src/createHistoWithMultiDraw.cpp

Added tool to split the histogram filling and to send jobs on condor. See histFactory/condorExample.py for usage.
To make this possible, createHistoWithMultiDraw.cpp is modified to add:
- possibility to specify output file (behavious stays the same as before if nothing is specified): option -o
- possiblity to specify which input files to run on in the input JSON ("files" entry). If the "path" entry is present in the JSON, default behavious is as before: all the root files in that folder are used.

Added condor utility

---

histFactory/CMakeLists.txt
histFactory/condorTools.py
histFactory/src/createHistoWithMultiDraw.cpp
histFactory/test/plots.py
histFactory/test/sample.json

A 'run' consists of a set of options which are passed to the python
script, which can be used to customize the set of plots to produce,
or change the cuts, or basically anything the user wants. The script
will be executed N times for each dataset, one time per run specified.
Runs are specified in the input JSON file, see `test/sample.json` for an
example.
The plots for all the various runs are done within the same event
loop, so if only the cut string is changed, runtime penalty should
be really small. Each set of plots for each run is saved in its own
file. You don't have to worry about name collision in different run,
it's handled automatically by the code to ensure each name are unique
during the plotting. Correct names are restored when saved into the output file.
Run options are …

Support for multiple runs per dataset

---

histFactory/src/createHistoWithMultiDraw.cpp

Since introduction of multi-run, binning and range are no longer respected. It's because now the histogram names are changed to a random string to prevent clashes between runs. This string is generated with `uuid_unparse`, which returns a C string of 36 characters, plus a NULL terminator. However, `std::string` are not NULL terminated, so when concatenating this string with something (binning and range for example...) and converting it to C string (the one ROOT uses), you basically introduce a NULL character in the middle of your string.
Long story short, this PR removes the null terminator from the string.
Thanks to @swertz for spotting this issue.

Ensure binning and range info are respected

---

histFactory/README.md
histFactory/cmake/modules/BuildExternals.cmake
histFactory/scripts/createPlotter.sh.in
histFactory/src/config.h.in
histFactory/src/createHistoWithMultiDraw.cpp
histFactory/src/createPlotter.cpp
histFactory/templates/CMakeLists.txt
histFactory/templates/Plot.tpl
histFactory/templates/Plotter.cc.tpl
histFactory/templates/Plotter.h.tpl
histFactory/templates/SavePlot.tpl
histFactory/templates/generateHeader.sh

The code is generated on-the-fly for a given set of plots. Once
compiled, the executable can run on any dataset and produce the
requested plots.
I checked that the resulting histograms are exactly the same as those produced by the multi-draw tool. Concerning the runtime, I found a gain of about 40x while plotting ~500 histograms from a tree of 15k entries. I was also able to draw ~16k plots from the same tree in 19s, but in this case, the resulting C++ code was a file of 6 MB!
It was also successfully used by @BrieucF and @swertz.
I've updated the README with some instructions on how-to use it. I hope it's still user-friendly enough!
PS: Don't look too much at the generated code, it's ugly as hell. Unfortunately, the template library does not do automatic indentation :smile:

New plotting utility in plain C++

---

histFactory/scripts/createPlotter.sh.in
histFactory/scripts/parallelizedPlotter.py.in
histFactory/templates/CMakeLists.txt

This script will be located in the same directory as `plotter.exe`. Usage is simple:
```
./parallelizedPlotter.py <myjson1> <myjson2> [...] -j 15
```
This will run the plotter on all datasets specified by the two files (one plotter instance per dataset) on 15 cores (so 15 instances in parallel).
If the `-j` option is missing, it runs on 4 cores.

Add small script to run over multiple datasets in parallel

---

histFactory/src/createPlotter.cpp
histFactory/templates/Plot.tpl
histFactory/templates/Plotter.cc.tpl
histFactory/templates/Plotter.h.tpl

Another round of improvements for the plotter, in commit order:
- Setup a 10 MB cache when reading the tree.
- Plotting collections is now supported. Suppose you have a branch of type `std::vector<float>` named `jet_pt`, you can directly plot `jet_pt`. It works only for simple array, expressions like `jet_p4.Pt()` are not supported since they are not valid C++ (`std::vector` has no member named `Pt`) and for 1D histograms.
- 2D and 3D histograms are now supported, same syntax as `TTree::Draw` (`x:y` or `x:y:z`).
- Title and axis labels can now be set for each histogram in the python configuration, using `title`, `x-axis`, `y-axis` and `z-axis` attributes.

2d plots and more

---

histFactory/createSampleJson.py
histFactory/templates/Plotter.cc.tpl
histFactory/templates/Plotter.h.tpl
histFactory/templates/SavePlot.tpl

Since we access the database to create the JSON sample file, it's easier to also retrieve the dataset cross-section and the sum of weights at this step than later when using plotIt.
Rescale all histograms with a factor `xsection / sum of weights`.

Rescale histograms using cross-section and sum of weights

---

histFactory/templates/CMakeLists.txt
histFactory/templates/Plotter.cc.tpl
histFactory/templates/Plotter.h.tpl

Use a TTreeFormula to evaluate a sample cut, specified in the sample JSON, when running the generated plotter.
If the output name is retrieved from the database, the "suffix" field can be used in the JSON to modify the output name accordingly.
This allows to do some of the things that were possible using the "runs" of createHistoWithMultiDraw.

Added sample cut for plotter

---

histFactory/src/createPlotter.cpp
histFactory/templates/Plot.tpl
histFactory/templates/Plotter.cc.tpl

It's not really practical to have the same line of code for the cut string and the weight. This commit separate the two by letting the python configuration to specify both a cut and a weight. If no weight is specified, 1 is used by default.
The weight is specified using the new `weight` entry in the dictionary. This formula is only evaluated iif the cut passed.
Also, as a side effect, I've changed the token used to split 2D and 3D histogram. Previously, it was `:`, but it's now `:::` (3 `:`), because `:` is valid C++ and strings like `(test ? 1. : 0.)` were split in two...
**Note**: all the python configuration will need to be updated to match the new expectation of the code. The `plot_cut` entry is now a `bool`, so you must removed any weight here. Specify your weights using the new …

Separate weight from cut string

---

histFactory/condorTools.py
histFactory/templates/Plotter.cc.tpl

Rarely, I've seen some cases where a job running on condor failed to open one or many (but not all) input files. The job would still succeed, but some events will be missing and it's really hard to detect, except inspecting all the error logs of all the jobs.
This is what this PR does. Before merging the files, it checks that all the error logs of all jobs are empty. If not, it warns the user and exit, otherwise, the files are merged as usual.

Add basic error detection in condor tools

---

histFactory/plots/TTAnalysis/ScaleFactors.py
histFactory/plots/TTAnalysis/TTAnalysis.py
histFactory/plots/TTAnalysis/basePlots.py
histFactory/plots/TTAnalysis/generatePlots.py
histFactory/plots/TTAnalysis/plotTools.py

Note: based on #57 
As title say, introduce basic support for SF for the TTAnalysis. It not as flexible as I'd hoped, and it'll break if we decide to not use the first di-lepton / di-jet pair, but for the moment it'll do the job.
Since we use an easy selection SFs wise, the following weights are applied:
- di-lepton categories: product of the leptons SFs
- di-lepton and at least 2 b-jets categories: product of the lepton SFs and b-tag SFs
Some are possibly missing, can you have a look @swertz?

[TTAnalysis] Basic scale factors support

---

.travis.yml
histFactory/CMakeLists.txt
histFactory/src/createPlotter.cpp
histFactory/src/formula_parser.cpp
histFactory/src/formula_parser.h

Introduce a small parser instead of using TTreeFormula for parsing
expressions. This has some benefits:
- It's (a lot) faster
- It handles all valid C expressions (does not handle namespaces for the moment, but can be added if needed)
- It does not complain on unknown identifiers
The only drawback is that compilation time for the `createPlotter`
tool is now a bit longer than before.
This will be useful for @swertz upcoming feature to allow inclusion of user specific code into the plotter.
It'd be great if someone other than @swertz can test, in order to see if others plots are nicely handled by the new parser.

Get rid of TTreeFormula for parsing expression

---

treeFactory/resubmit.py

This is a script allowing to resubmit the failed jobs on condor (see PR #59 ). It is a bit ugly but it should work. Here is an example how to use it from treeFactory : 
`python resubmit.py sameFlavour_2016_01_06/condor/` [submit]
The optional `submit` should be put only if you want the failed jobs to be actually resubmitted.
I have tested it from histFactory with : 
`python ../treefactory/resubmit.py sameFlavour_2016_01_06/condor/` [submit]
and it worked as well. Hope it can be useful for you as well.

resubmit script

---

common/include/formula_parser.h
treeFactory/test/tree.py

Some expressions like `!expr`, `~expr` or `++expr` failed to parse

Improve parser reliability

---

.travis.yml

Currently, only `histFactory` is built on Travis. This PR adds `treeFactory` to CI. Both are built in parallel using Travis matrix :)
You can see the typical output here: https://travis-ci.org/cp3-llbb/CommonTools/builds/101888545

Build treeFactory in travis too

---

mvaTraining/tmvaTools.py

Turn the arguments of ```MVA_out_in_tree``` into a tuple to allow multiprocessing using Pool(). Also make TMVA Reader silent to avoid prompt flood.

Silent and parallel BDT merging

---

histFactory/CMakeLists.txt
histFactory/templates/CMakeLists.txt.tpl
treeFactory/CMakeLists.txt
treeFactory/templates/CMakeLists.txt

There's an issue while looking for boost  with cmake 2.6 and the build fails with **cryptic** errors, so, until I found a proper fix, just bump the cmake version to 2.8 to remind the user to use `cmake28` instead of `cmake`

Bump min. cmake version to 2.8

---

histFactory/templates/CMakeLists.txt.tpl
treeFactory/templates/CMakeLists.txt

I was a bit to prompt when I bumped minimum version to 2.8. It's not needed for plotters / skimmers build, and it actually breaks everything, sorry!

cmake 2.6 is enough to build plotters / skimmers

---

histFactory/scripts/createPlotter.sh.in

clang is faster to build large source than gcc. For ~800 plots:
- clang: 55.944s
- gcc: 1min 20.18s

Build plotter with clang if available

---

histFactory/templates/Plotter.cc.tpl

Reduces root verbosity so that warnings due to addition of empty files does not end up in the condor.err (this was spoiling the check for failed jobs).

'Fix' for empty rootfile

---

histFactory/condorTools.py
histFactory/src/createPlotter.cpp
histFactory/templates/EnsureNormalization.tpl
histFactory/templates/Plotter.cc.tpl
histFactory/templates/Plotter.h.tpl
histFactory/templates/SavePlot.tpl
histFactory/test/plots.py
scripts/createSampleJson.py

First commit adds support for extra sum of event weights introduced in https://github.com/cp3-llbb/Framework/pull/147, https://github.com/cp3-llbb/SAMADhi/pull/11 and https://github.com/cp3-llbb/GridIn/pull/69 in the sample JSON file.
Second commit adds support for normalization others than nominal in histFactory. To do this, a new option is added to the python definition of plots, `normalize-to`. Default value is `nominal` so nothing change, but you can also specify for example `pdf_up` or `pdf_down` to normalize wrt the sum of event weight for PDF up or down.
Based on @AlexandreMertens suggestion, I also added a 'is-data' flag to the input JSON file. Rescaling of histograms occurs only if running over MC, not over data, so it's safe to use the `normalize-to` option even on data.

Support alternative normalization in histFactory

---

scripts/createScaleSystematics.py
scripts/getEnvelopHistogram.py

There's two new scripts:
- `getEnvelopHistogram.py`: a generic tool to compute an envelop from a set of histograms
- `createScaleSystematics.py`: a wrapper around `getEnvelopHistogram.py` dedicated only to scale systematics.
Usage is easy:
```bash
./createScaleSystematics.py INPUT.root my_nominal_histogram
```
The script will look in `INPUT.root` for all the scale variations (**must** be named in this case `my_nominal_histogram__scale0`, `my_nominal_histogram__scale1`, ..., `my_nominal_histogram__scale5`), and create the envelop histograms, named in this case `my_nominal_histogram__scaleup` and `my_nominal_histogram__scaledown`. These histograms will be saved directly in the input file (so the content of the file is modified).
It gives this results (tested on a DY file borrowed from …

Add helper to create scale variation systematic histograms

---

histFactory/condorTools.py
scripts/createSampleJson.py

@BrieucF found a bug when the extras sum of weights database column is not filled. This protects against such cases.

Protect code over possible None extra sumw

---

histFactory/templates/Plotter.cc.tpl
treeFactory/templates/Skimmer.cc.tpl

@BrieucF realized that ROOT prints error message to stderr when failing to add a file to the TChain. So, even if we try 5 times to open the files, if it fails once, then the post-job script will flag these jobs as failed since there's text in stderr even if they are in fine good.
This PR fixes this behavior by silenting ROOT errors during the TChain::Add. I also increased the sleeping time from 300ms -> 1.5s to 1s -> 30s.

Silent ROOT error when trying to open chain files

---

histFactory/src/createPlotter.cpp
histFactory/templates/Plotter.cc.tpl

Add the possibility to insert user code in the plotter: before, inside, and after the loop over the events (e.g. to define variables used in the histograms, or load information from files, ...). 
This code is defined in the python configuration through the 3 **strings** "code_before_loop", "code_in_loop" and "code_after_loop". Of course, nothing prevents the user to retrieve this code from external files in the python code itself, if defining strings is impractical.
Also, slightly change the way C++ header files are included in the plotter (variable "includes" in the python file): if a headers contains a "<", ie is a library header (e.g. "<TH2.h>" instead of just "TH2.h"), no attempt is made to check the path to the header.

Include user code in the plotter itself

---

histFactory/src/createPlotter.cpp
scripts/addHistos.py

This PR does two things:
- fix the inclusion of library header files, which was buggy in #102 
- add a helper script to merge histograms: "addHistos.py". Usage:
`./addHistos.py -i (input file) -o (output file) -c (config file)`
where config file is a python file containing e.g.:
```
toJoin = [
{
"match": r"DR_b(bar)?_CAT.*", 
"newName": "DR_gen_matched",
"veto": r".*ZVeto.*",
"normalise": True,
}
]
```
All histograms in the input file matching the regexp "match" will be added and written as the new histogram "newName" in the output file. The non-mandatory fields "veto" and "normalise" respectively allow to veto histograms matching the regex, and normalise the resulting histogram.

Fix header files + script to add histos

---

histFactory/src/createPlotter.cpp
scripts/addHistos.py
scripts/checkJobsAndResubmit.py
treeFactory/CMakeLists.txt
treeFactory/scripts/createSkimmer.sh.in
treeFactory/src/createSkimmer.cc
treeFactory/templates/CMakeLists.txt.tpl
treeFactory/templates/Skimmer.cc.tpl

* Port features added in #103 , #102 and #67 (allowing to include external files/code and extra branches in the plotter) to treeFactory.
* Move @BrieucF 's `resubmit.py` to a more suitable folder and rename it (it can be used for both plotter and skimmer).
* Make treeFactory's directory structure more similar to histFactory's one. And I'm thinking we could at some point move some of the common code to a ... common folder, since there is already some duplication.
* Also, it would be good if @BrieucF  or @OlivierBondu  could move the HH folder from treeFactory to their HH repo...

Port features to treeFactory

---

treeFactory/src/createSkimmer.cc
treeFactory/test/tree.py

treeFactory: add possibility to specify output branch type, using the field "type" in the python config, e.g.:
```
"branches": [
{
"name": "test",
"variable": "is_data",
"type": "bool",
}
]
```
Maybe not very useful for a bool, but can be useful for storing e.g. LorentzVectors...

Custom output branch type

---

histFactory/src/createPlotter.cpp
histFactory/templates/SavePlot.tpl
histFactory/test/plots.py

An new option is available for the python configuration, `folder`, which specify in which folder the histogram must be saved. This option support multiple folders, separated with a `/`, like `my/folder`. If not specified, the histogram will be saved at the root of the file, as usual.

[HistFactory] add a way to store histograms in folders

---

histFactory/src/createPlotter.cpp
histFactory/templates/Plot.tpl
histFactory/templates/Plotter.cc.tpl
histFactory/templates/Plotter.h.tpl
histFactory/test/plots.py
histFactory/test/sample.json

The weights expressions must be defined in the python configuration,
through the `sample_weights` dictionnary. The key is an identifier, and
the value the expression of the weight.
In the sample json, one can use one of the key defined in the python
configuration for the new `sample-weight` option. The weight evaluated
from the expression will be used to scale all the histograms. If set to
`none` or not specified, a default weight of 1 is applied.
--
Example:
In python, one can do
```python
sample_weights = {
'cluster_1': 'getWeightForCluster(1)',
'cluster_2': 'getWeightForCluster(2)'
}
```
In the sample json, you can apply a given sample weight using the `sample-weight` option. It can be either `cluster_1`, or `cluster_2`.
```json
{ …
```

[HistFactory] add support for sample weights

---

python/CMSStyle.py

A small python macro to customize a matplotlib figure to the CMS style.
Usage:
```python
import matplotlib.pyplot as plt
import cp3_llbb.CommonTools.CMSStyle as CMSStyle
CMSStyle.changeFont()
fig, ax = plt.subplots()
CMSStyle.applyStyle(fig, ax, lumi=2700)
```
The text is placed automatically based on the axes position. If you change the margins, the text won't be updated, so it's best to called the `applyStyle` function at the end of the plotting.

Python function to add CMS style to a matplotlib figure

---

scripts/createScaleSystematics.py

Slight update to 'createScaleSystematics' to merge a different systematics than `scale`, for instance call the script with `-s scaleUncorr` to get the envelopes for the `scaleUncorr` variations.

Slight update to createScaleSystematics

---

histFactory/condorTools.py
histFactory/templates/Plotter.cc.tpl
histFactory/templates/Plotter.h.tpl
histFactory/test/plots.py
histFactory/test/sample.json
treeFactory/templates/Skimmer.cc.tpl
treeFactory/templates/Skimmer.h.tpl

PR is in two parts:
1. Add necessary code into histFactory / treeFactory to handle starting and ending entry for the event loop
2. Add a new option in condor tools, `events_per_jobs`.
It's probably possible to do the same thing smartly, but at least it's working :) I tested it with histFactory doing a plot splitting either per files or per events, and I got exactly the same histograms :+1: 
Note that this PR depends on a updated version of TreeWrapper: https://github.com/blinkseb/TreeWrapper/commit/f15829c381c14f48edd98aed47979d427ce8ac28

Add a way to split jobs per events instead of files

---

histFactory/condorTools.py

Truncate file list according to the required fraction specified by the user in the sample config via `sample["sample_fraction"]`. NB : the processed fraction will not equal exactly nEvt_tot*fraction event, it is rounded up to nEvt_tot * fraction + nEvt in next file. The sum of event weights is recomputed accordingly.

Add possibility to run over fraction of sample

---

Factories/README.md
Factories/scripts/createFactory.sh.in
Factories/src/HistFactory.cc
Factories/templates/CMakeLists.txt.tpl
Factories/templates/Main.cc.tpl
Factories/templates/Main.h.tpl

Small fixes:
-The field `plot_cut` in the `plots` variable in the python config had become mandatory when it shouldn't be
- The fields `is-data` and `db-name` in the sample JSONS do not have to be mandatory
It's now possible to use HistFactory and TreeFactory completely outside of CMSSW. Only thing that is needed is Seb's `TreeWrapper` library, and some tweaks to link to the latter when running `createPlotter` (see README).

Small fixes; fix use outside of CMSSW

---

Factories/include/Factory.h
Factories/include/TreeFactory.h
Factories/src/Factory.cc
Factories/src/HistFactory.cc
Factories/src/TreeFactory.cc
Factories/templates/Main.cc.tpl
Factories/test/sample.json
Factories/test/tree.py

Useful to simply add branches into an existing tree while applying a set of cuts. Simply turn the flag `clone` in the `tree` dict to enable this feature.
Second commit is unrelated but fix an issue in histFactory mode

Add a way to clone the input tree when skimming

---

Factories/cmake/modules/BuildExternals.cmake
Factories/templates/CMakeLists.txt.tpl
Factories/templates/Main.h.tpl

This PR decouples again a bit more `Factories` from CMSSW by always building TreeWrapper as an external dependency, even within CMSSW. The mid-term vision here is to be able to build the plotter / skimmer with a different version of ROOT than the one shipped with CMSSW and for that, one has to be sure that all the libraries are built against the same version of ROOT, which is not the case if we use the TreeWrapper built within CMSSW.

Build TreeWrapper as external even within CMSSW

---

python/HistogramTools.py
scripts/flattenDistribution.py
toolBox/drawCanvas.py

- Add script finding bin limits to flatten a distribution
- A few fixes to the tool used to quickly draw not too ugly TGraphs, add possibility to have a ratio plot
- New function in HistogramTools: retrieve all TH1 objects from a file, whose name matches a regex

Flatten variable; ratio plots for graphs

---

Factories/README.md
Factories/include/Factory.h
Factories/include/HistFactory.h
Factories/src/HistFactory.cc
Factories/templates/Main.cc.tpl
Factories/templates/Main.h.tpl
Factories/templates/PlotNoCheckData.tpl

Add new, non-mandatory field in the plots entries for HistFactory: `allow-weighted-data`. If set to `True` for a plot, the weight applied to that plot will not be forced to 1 when running on data.
Given the discussion in #136 and @blinkseb's input, this seems the most straightforward solution if one wants to avoid generating two separate plotters to derive data-driven estimates.
Also, allow passing arguments to the functions returning so-called sample weights. Those arguments can be passed as a list of strings in the dataset JSON (new entry: `sample-weight-args`), and will be available inside the function returning the sample weight as a vector of strings called `sample_weight_args`
Note: based on #135

Possibily to weight data; arguments to sample weights

---

Factories/src/TreeFactory.cc
python/condorTools.py

I had tested #137 for the plotter, not for the skimmer: something was missing (sorry).
A small tweak to the script doing the hadd of the factories' output: if only one file is to be hadd'ed, do not call `hadd` but simply rename it: much faster, especially when we have hundreds of signal files with only one job per sample!

Fix skimmer; faster hadd

---

Factories/templates/CMakeLists.txt.tpl

Even with -O1, the compilation time when there's more than ~100
histograms gets out of control (> 20h). Instead of penalizing every source file, turn on optimizations for everything, and turn off only for the main file.

[Factories] Turn on compiler optimizations expect for main file

---

Factories/templates/CMakeLists.txt.tpl
toolBox/drawCanvas.py

Link produced factories with GSL by default. It's installed on most systems and present in CMSSW.
Completely different but not worth a separate PR: the default colors for the "drawTGraph" utility now come from https://github.com/vega/vega/wiki/Scales#scale-range-literals

Link factories with GSL

---

python/CMSStyle.py

Default to 1 now instead of 2, but user controllable

Add a way to control the number of figures used to display luminosity

---

scripts/checkJobsAndResubmit.py

This PR extends the existing script by looking also in the stdout job output to check for possible error by grepping common keywords like `error`, `warning` or `fail`.

Also check job stdout for possible error

---

Factories/README.md
Factories/cmake/modules/BuildExternals.cmake

update to the changes in https://github.com/blinkseb/TreeWrapper/pull/3, so don't merge before that ;)
I also took the opportunity to silence the stderr for ctemplate-configure, such that you can continue using the same shell after that.

Build TreeWrapper (as external for Factories) with cmake
